# Generated by Django 5.0.7 on 2024-07-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="habitentry",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="habit",
            name="description",
        ),
        migrations.AlterField(
            model_name="habit",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
