# Generated by Django 5.0.7 on 2024-07-26 20:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_alter_habitentry_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="habitentry",
            name="status",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="habit",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
