# Generated by Django 5.0.7 on 2024-07-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_habit_description_habitentry_status_alter_habit_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="habitentry",
            name="customValue",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
