# Generated by Django 5.0.7 on 2024-08-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_habitentry_customvalue"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("completed", models.BooleanField(default=False)),
                ("date", models.DateField()),
                ("day_of_week", models.CharField(max_length=10)),
            ],
        ),
    ]
