# Generated by Django 5.0.7 on 2024-08-08 22:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0005_task"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="description",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="task",
            name="day_of_week",
        ),
    ]
