# Generated by Django 5.0.7 on 2024-08-09 06:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0006_rename_description_task_name_remove_task_day_of_week"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
