# Generated by Django 5.0.7 on 2024-08-28 23:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0008_journalentry"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="time",
            new_name="time_start",
        ),
        migrations.AddField(
            model_name="task",
            name="time_end",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
